serial:
  port: '/dev/ttyUSB0'

run:
  sleep_time: 2
  calculation_trusted_delay: 60

# possible values: mqtt, influx
backend: mqtt

mqtt:
  hostname: '192.168.1.1'
  username: 'usr'
  password: 'passwd'

influx:
  hostname: 'http://192.168.1.1:8086'
  bucket:   ''
  token:    ''
  org:      ''

adc:
  battery_voltage_max: 17.35

discharge_config:
  full_voltage: 25.6  # 12.8
  empty_voltage: 11.0  # 10.5

charge_config:
  float_current: 1.0  # 6.0
  full_voltage: 27.2  # 13.6
  boost_voltage: 28.8  # 14.4
  empty_voltage: 11.0  # 10.5

trigger:
  enable: True
  command:
    - 'shutdown'
    - 'now'
  voltage: 20.0  # 10.7
