serial:
  port: '/dev/ttyUSB0'

run:
  sleep_time: 2

discharge_config:
  full_voltage: 25.6  # 12.8
  empty_voltage: 11.0  # 10.5

charge_config:
  float_current: 1.0  # 6.0
  full_voltage: 27.2  # 13.6
  boost_voltage: 28.8  # 14.4
  empty_voltage: 11.0  # 10.5

energy: False

sensors:
  - 'battery_level'
  - 'battery_voltage'
  - 'charging_current'
  - 'input_voltage'
  - 'load_current'
  - 'load_level'
  - 'output_power'
  - 'output_voltage'
  - 'ups_temperature'

debug: off

# possible values: mqtt, influx
backend: mqtt

trigger:
  enable: True
  command:
    - 'shutdown'
    - 'now'
  voltage: 20.0  # 10.7

mqtt:
  hostname: '192.168.1.1'
  username: 'usr'
  password: 'passwd'

influx:
  hostname: 'http://192.168.1.1:8086'
  bucket:   ''
  token:    ''
  org:      ''
